// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq9lNTEGAuSJjdpZaMR_kQ6tWpNi-gF9Y',
    appId: '1:307475931590:web:a2daf0d3fd57360ce7d2c7',
    messagingSenderId: '307475931590',
    projectId: 'fitherb',
    authDomain: 'fitherb.firebaseapp.com',
    storageBucket: 'fitherb.firebasestorage.app',
    measurementId: 'G-49S2827ZJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwn82vKR--S2k9jIpVM6hKr81cvHiRXXs',
    appId: '1:307475931590:android:657013d4a088d05be7d2c7',
    messagingSenderId: '307475931590',
    projectId: 'fitherb',
    storageBucket: 'fitherb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSBTv41cw9jTmJbqNqdLU4-EYv-0q_kFE',
    appId: '1:307475931590:ios:245625d29347cce9e7d2c7',
    messagingSenderId: '307475931590',
    projectId: 'fitherb',
    storageBucket: 'fitherb.firebasestorage.app',
    iosBundleId: 'com.example.newFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSBTv41cw9jTmJbqNqdLU4-EYv-0q_kFE',
    appId: '1:307475931590:ios:91af24972f19603be7d2c7',
    messagingSenderId: '307475931590',
    projectId: 'fitherb',
    storageBucket: 'fitherb.firebasestorage.app',
    iosBundleId: 'com.example.yummy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq9lNTEGAuSJjdpZaMR_kQ6tWpNi-gF9Y',
    appId: '1:307475931590:web:d1a67960314f8be2e7d2c7',
    messagingSenderId: '307475931590',
    projectId: 'fitherb',
    authDomain: 'fitherb.firebaseapp.com',
    storageBucket: 'fitherb.firebasestorage.app',
    measurementId: 'G-R4DLBMMPNR',
  );
}
